# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from omni_pro_grpc.v1.rules import (
    template_special_conditions_pb2 as v1_dot_rules_dot_template__special__conditions__pb2,
)


class TemplateSpecialConditionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TemplateSpecialConditionsCreate = channel.unary_unary(
            "/pro.omni.oms.api.v1.rules.template_special_conditions.TemplateSpecialConditionsService/TemplateSpecialConditionsCreate",
            request_serializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsCreateRequest.SerializeToString,
            response_deserializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsCreateResponse.FromString,
        )
        self.TemplateSpecialConditionsRead = channel.unary_unary(
            "/pro.omni.oms.api.v1.rules.template_special_conditions.TemplateSpecialConditionsService/TemplateSpecialConditionsRead",
            request_serializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsReadRequest.SerializeToString,
            response_deserializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsReadResponse.FromString,
        )
        self.TemplateSpecialConditionsUpdate = channel.unary_unary(
            "/pro.omni.oms.api.v1.rules.template_special_conditions.TemplateSpecialConditionsService/TemplateSpecialConditionsUpdate",
            request_serializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsUpdateRequest.SerializeToString,
            response_deserializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsUpdateResponse.FromString,
        )
        self.TemplateSpecialConditionsDelete = channel.unary_unary(
            "/pro.omni.oms.api.v1.rules.template_special_conditions.TemplateSpecialConditionsService/TemplateSpecialConditionsDelete",
            request_serializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsDeleteRequest.SerializeToString,
            response_deserializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsDeleteResponse.FromString,
        )


class TemplateSpecialConditionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TemplateSpecialConditionsCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TemplateSpecialConditionsRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TemplateSpecialConditionsUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TemplateSpecialConditionsDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TemplateSpecialConditionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "TemplateSpecialConditionsCreate": grpc.unary_unary_rpc_method_handler(
            servicer.TemplateSpecialConditionsCreate,
            request_deserializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsCreateRequest.FromString,
            response_serializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsCreateResponse.SerializeToString,
        ),
        "TemplateSpecialConditionsRead": grpc.unary_unary_rpc_method_handler(
            servicer.TemplateSpecialConditionsRead,
            request_deserializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsReadRequest.FromString,
            response_serializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsReadResponse.SerializeToString,
        ),
        "TemplateSpecialConditionsUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.TemplateSpecialConditionsUpdate,
            request_deserializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsUpdateRequest.FromString,
            response_serializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsUpdateResponse.SerializeToString,
        ),
        "TemplateSpecialConditionsDelete": grpc.unary_unary_rpc_method_handler(
            servicer.TemplateSpecialConditionsDelete,
            request_deserializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsDeleteRequest.FromString,
            response_serializer=v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsDeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pro.omni.oms.api.v1.rules.template_special_conditions.TemplateSpecialConditionsService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class TemplateSpecialConditionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TemplateSpecialConditionsCreate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.rules.template_special_conditions.TemplateSpecialConditionsService/TemplateSpecialConditionsCreate",
            v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsCreateRequest.SerializeToString,
            v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def TemplateSpecialConditionsRead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.rules.template_special_conditions.TemplateSpecialConditionsService/TemplateSpecialConditionsRead",
            v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsReadRequest.SerializeToString,
            v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def TemplateSpecialConditionsUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.rules.template_special_conditions.TemplateSpecialConditionsService/TemplateSpecialConditionsUpdate",
            v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsUpdateRequest.SerializeToString,
            v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def TemplateSpecialConditionsDelete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.rules.template_special_conditions.TemplateSpecialConditionsService/TemplateSpecialConditionsDelete",
            v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsDeleteRequest.SerializeToString,
            v1_dot_rules_dot_template__special__conditions__pb2.TemplateSpecialConditionsDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
