# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from omni_pro_grpc.v1.stock import barcode_pb2 as v1_dot_stock_dot_barcode__pb2


class BarcodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BarcodeCreate = channel.unary_unary(
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeCreate",
            request_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeCreateRequest.SerializeToString,
            response_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeCreateResponse.FromString,
        )
        self.BarcodeRead = channel.unary_unary(
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeRead",
            request_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeReadRequest.SerializeToString,
            response_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeReadResponse.FromString,
        )
        self.BarcodeUpdate = channel.unary_unary(
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeUpdate",
            request_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeUpdateRequest.SerializeToString,
            response_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeUpdateResponse.FromString,
        )
        self.BarcodeDelete = channel.unary_unary(
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeDelete",
            request_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeDeleteRequest.SerializeToString,
            response_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeDeleteResponse.FromString,
        )
        self.BarcodeLineCreate = channel.unary_unary(
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeLineCreate",
            request_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineCreateRequest.SerializeToString,
            response_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineCreateResponse.FromString,
        )
        self.BarcodeLineRead = channel.unary_unary(
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeLineRead",
            request_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineReadRequest.SerializeToString,
            response_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineReadResponse.FromString,
        )
        self.BarcodeLineUpdate = channel.unary_unary(
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeLineUpdate",
            request_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineUpdateRequest.SerializeToString,
            response_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineUpdateResponse.FromString,
        )
        self.BarcodeLineDelete = channel.unary_unary(
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeLineDelete",
            request_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineDeleteRequest.SerializeToString,
            response_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineDeleteResponse.FromString,
        )


class BarcodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BarcodeCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BarcodeRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BarcodeUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BarcodeDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BarcodeLineCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BarcodeLineRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BarcodeLineUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BarcodeLineDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BarcodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "BarcodeCreate": grpc.unary_unary_rpc_method_handler(
            servicer.BarcodeCreate,
            request_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeCreateRequest.FromString,
            response_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeCreateResponse.SerializeToString,
        ),
        "BarcodeRead": grpc.unary_unary_rpc_method_handler(
            servicer.BarcodeRead,
            request_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeReadRequest.FromString,
            response_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeReadResponse.SerializeToString,
        ),
        "BarcodeUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.BarcodeUpdate,
            request_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeUpdateRequest.FromString,
            response_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeUpdateResponse.SerializeToString,
        ),
        "BarcodeDelete": grpc.unary_unary_rpc_method_handler(
            servicer.BarcodeDelete,
            request_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeDeleteRequest.FromString,
            response_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeDeleteResponse.SerializeToString,
        ),
        "BarcodeLineCreate": grpc.unary_unary_rpc_method_handler(
            servicer.BarcodeLineCreate,
            request_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineCreateRequest.FromString,
            response_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineCreateResponse.SerializeToString,
        ),
        "BarcodeLineRead": grpc.unary_unary_rpc_method_handler(
            servicer.BarcodeLineRead,
            request_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineReadRequest.FromString,
            response_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineReadResponse.SerializeToString,
        ),
        "BarcodeLineUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.BarcodeLineUpdate,
            request_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineUpdateRequest.FromString,
            response_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineUpdateResponse.SerializeToString,
        ),
        "BarcodeLineDelete": grpc.unary_unary_rpc_method_handler(
            servicer.BarcodeLineDelete,
            request_deserializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineDeleteRequest.FromString,
            response_serializer=v1_dot_stock_dot_barcode__pb2.BarcodeLineDeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pro.omni.oms.api.stock.barcode.BarcodeService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class BarcodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BarcodeCreate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeCreate",
            v1_dot_stock_dot_barcode__pb2.BarcodeCreateRequest.SerializeToString,
            v1_dot_stock_dot_barcode__pb2.BarcodeCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def BarcodeRead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeRead",
            v1_dot_stock_dot_barcode__pb2.BarcodeReadRequest.SerializeToString,
            v1_dot_stock_dot_barcode__pb2.BarcodeReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def BarcodeUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeUpdate",
            v1_dot_stock_dot_barcode__pb2.BarcodeUpdateRequest.SerializeToString,
            v1_dot_stock_dot_barcode__pb2.BarcodeUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def BarcodeDelete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeDelete",
            v1_dot_stock_dot_barcode__pb2.BarcodeDeleteRequest.SerializeToString,
            v1_dot_stock_dot_barcode__pb2.BarcodeDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def BarcodeLineCreate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeLineCreate",
            v1_dot_stock_dot_barcode__pb2.BarcodeLineCreateRequest.SerializeToString,
            v1_dot_stock_dot_barcode__pb2.BarcodeLineCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def BarcodeLineRead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeLineRead",
            v1_dot_stock_dot_barcode__pb2.BarcodeLineReadRequest.SerializeToString,
            v1_dot_stock_dot_barcode__pb2.BarcodeLineReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def BarcodeLineUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeLineUpdate",
            v1_dot_stock_dot_barcode__pb2.BarcodeLineUpdateRequest.SerializeToString,
            v1_dot_stock_dot_barcode__pb2.BarcodeLineUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def BarcodeLineDelete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.stock.barcode.BarcodeService/BarcodeLineDelete",
            v1_dot_stock_dot_barcode__pb2.BarcodeLineDeleteRequest.SerializeToString,
            v1_dot_stock_dot_barcode__pb2.BarcodeLineDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
