# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/stock/channel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from omni_pro_grpc.common import base_pb2 as common_dot_base__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16v1/stock/channel.proto\x12!pro.omni.oms.api.v1.stock.channel\x1a\x11\x63ommon/base.proto\x1a\x1egoogle/protobuf/wrappers.proto"\xcb\x01\n\x07\x43hannel\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x16\n\x0e\x63hannel_sql_id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12*\n\x06\x61\x63tive\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x13\n\x0b\x65xternal_id\x18\x07 \x01(\t\x12?\n\x0cobject_audit\x18\x08 \x01(\x0b\x32).pro.omni.oms.api.common.base.ObjectAudit"\x8b\x01\n\x14\x43hannelUpdateRequest\x12;\n\x07\x63hannel\x18\x01 \x01(\x0b\x32*.pro.omni.oms.api.v1.stock.channel.Channel\x12\x36\n\x07\x63ontext\x18\x02 \x01(\x0b\x32%.pro.omni.oms.api.common.base.Context"\x9f\x01\n\x15\x43hannelUpdateResponse\x12I\n\x11response_standard\x18\x01 \x01(\x0b\x32..pro.omni.oms.api.common.base.ResponseStandard\x12;\n\x07\x63hannel\x18\x02 \x01(\x0b\x32*.pro.omni.oms.api.v1.stock.channel.Channel"Z\n\x14\x43hannelDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x36\n\x07\x63ontext\x18\x02 \x01(\x0b\x32%.pro.omni.oms.api.common.base.Context"b\n\x15\x43hannelDeleteResponse\x12I\n\x11response_standard\x18\x01 \x01(\x0b\x32..pro.omni.oms.api.common.base.ResponseStandard2\x9e\x02\n\x0e\x43hannelService\x12\x84\x01\n\rChannelUpdate\x12\x37.pro.omni.oms.api.v1.stock.channel.ChannelUpdateRequest\x1a\x38.pro.omni.oms.api.v1.stock.channel.ChannelUpdateResponse"\x00\x12\x84\x01\n\rChannelDelete\x12\x37.pro.omni.oms.api.v1.stock.channel.ChannelDeleteRequest\x1a\x38.pro.omni.oms.api.v1.stock.channel.ChannelDeleteResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "v1.stock.channel_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _globals["_CHANNEL"]._serialized_start = 113
    _globals["_CHANNEL"]._serialized_end = 316
    _globals["_CHANNELUPDATEREQUEST"]._serialized_start = 319
    _globals["_CHANNELUPDATEREQUEST"]._serialized_end = 458
    _globals["_CHANNELUPDATERESPONSE"]._serialized_start = 461
    _globals["_CHANNELUPDATERESPONSE"]._serialized_end = 620
    _globals["_CHANNELDELETEREQUEST"]._serialized_start = 622
    _globals["_CHANNELDELETEREQUEST"]._serialized_end = 712
    _globals["_CHANNELDELETERESPONSE"]._serialized_start = 714
    _globals["_CHANNELDELETERESPONSE"]._serialized_end = 812
    _globals["_CHANNELSERVICE"]._serialized_start = 815
    _globals["_CHANNELSERVICE"]._serialized_end = 1101
# @@protoc_insertion_point(module_scope)
