# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from omni_pro_grpc.v1.stock import integration_operation_pb2 as v1_dot_stock_dot_integration__operation__pb2


class IntegrationOperationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IntegrationOperationCreate = channel.unary_unary(
            "/pro.omni.oms.api.v1.stock.integration_operation.IntegrationOperationService/IntegrationOperationCreate",
            request_serializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationCreateRequest.SerializeToString,
            response_deserializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationCreateResponse.FromString,
        )
        self.IntegrationOperationRead = channel.unary_unary(
            "/pro.omni.oms.api.v1.stock.integration_operation.IntegrationOperationService/IntegrationOperationRead",
            request_serializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationReadRequest.SerializeToString,
            response_deserializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationReadResponse.FromString,
        )
        self.IntegrationOperationUpdate = channel.unary_unary(
            "/pro.omni.oms.api.v1.stock.integration_operation.IntegrationOperationService/IntegrationOperationUpdate",
            request_serializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationUpdateRequest.SerializeToString,
            response_deserializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationUpdateResponse.FromString,
        )
        self.IntegrationOperationDelete = channel.unary_unary(
            "/pro.omni.oms.api.v1.stock.integration_operation.IntegrationOperationService/IntegrationOperationDelete",
            request_serializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationDeleteRequest.SerializeToString,
            response_deserializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationDeleteResponse.FromString,
        )


class IntegrationOperationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IntegrationOperationCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def IntegrationOperationRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def IntegrationOperationUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def IntegrationOperationDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_IntegrationOperationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "IntegrationOperationCreate": grpc.unary_unary_rpc_method_handler(
            servicer.IntegrationOperationCreate,
            request_deserializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationCreateRequest.FromString,
            response_serializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationCreateResponse.SerializeToString,
        ),
        "IntegrationOperationRead": grpc.unary_unary_rpc_method_handler(
            servicer.IntegrationOperationRead,
            request_deserializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationReadRequest.FromString,
            response_serializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationReadResponse.SerializeToString,
        ),
        "IntegrationOperationUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.IntegrationOperationUpdate,
            request_deserializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationUpdateRequest.FromString,
            response_serializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationUpdateResponse.SerializeToString,
        ),
        "IntegrationOperationDelete": grpc.unary_unary_rpc_method_handler(
            servicer.IntegrationOperationDelete,
            request_deserializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationDeleteRequest.FromString,
            response_serializer=v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationDeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pro.omni.oms.api.v1.stock.integration_operation.IntegrationOperationService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class IntegrationOperationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IntegrationOperationCreate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.stock.integration_operation.IntegrationOperationService/IntegrationOperationCreate",
            v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationCreateRequest.SerializeToString,
            v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def IntegrationOperationRead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.stock.integration_operation.IntegrationOperationService/IntegrationOperationRead",
            v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationReadRequest.SerializeToString,
            v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def IntegrationOperationUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.stock.integration_operation.IntegrationOperationService/IntegrationOperationUpdate",
            v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationUpdateRequest.SerializeToString,
            v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def IntegrationOperationDelete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.stock.integration_operation.IntegrationOperationService/IntegrationOperationDelete",
            v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationDeleteRequest.SerializeToString,
            v1_dot_stock_dot_integration__operation__pb2.IntegrationOperationDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
