# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/util/mirror_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from omni_pro_grpc.common import base_pb2 as common_dot_base__pb2
from omni_pro_grpc.v1.utilities import model_pb2 as v1_dot_utilities_dot_model__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1av1/util/mirror_model.proto\x12%pro.omni.oms.api.v1.util.mirror_model\x1a\x11\x63ommon/base.proto\x1a\x18v1/utilities/model.proto\x1a\x1cgoogle/protobuf/struct.proto"\x94\x01\n\x19\x43reateOrUpdateMirrorModel\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12+\n\nmodel_data\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x36\n\x07\x63ontext\x18\x03 \x01(\x0b\x32%.pro.omni.oms.api.common.base.Context"\x9c\x01\n"CreateOrUpdateCreateMirrorResponse\x12+\n\nmodel_data\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12I\n\x11response_standard\x18\x02 \x01(\x0b\x32..pro.omni.oms.api.common.base.ResponseStandard"r\n\x18\x44\x65leteMirrorModelRequest\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x36\n\x07\x63ontext\x18\x03 \x01(\x0b\x32%.pro.omni.oms.api.common.base.Context"f\n\x19\x44\x65leteMirrorModelResponse\x12I\n\x11response_standard\x18\x01 \x01(\x0b\x32..pro.omni.oms.api.common.base.ResponseStandard2\xf9\x03\n\x12MirrorModelService\x12\xa2\x01\n\x11\x43reateMirrorModel\x12@.pro.omni.oms.api.v1.util.mirror_model.CreateOrUpdateMirrorModel\x1aI.pro.omni.oms.api.v1.util.mirror_model.CreateOrUpdateCreateMirrorResponse"\x00\x12\xa2\x01\n\x11UpdateMirrorModel\x12@.pro.omni.oms.api.v1.util.mirror_model.CreateOrUpdateMirrorModel\x1aI.pro.omni.oms.api.v1.util.mirror_model.CreateOrUpdateCreateMirrorResponse"\x00\x12\x98\x01\n\x11\x44\x65leteMirrorModel\x12?.pro.omni.oms.api.v1.util.mirror_model.DeleteMirrorModelRequest\x1a@.pro.omni.oms.api.v1.util.mirror_model.DeleteMirrorModelResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "v1.util.mirror_model_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _globals["_CREATEORUPDATEMIRRORMODEL"]._serialized_start = 145
    _globals["_CREATEORUPDATEMIRRORMODEL"]._serialized_end = 293
    _globals["_CREATEORUPDATECREATEMIRRORRESPONSE"]._serialized_start = 296
    _globals["_CREATEORUPDATECREATEMIRRORRESPONSE"]._serialized_end = 452
    _globals["_DELETEMIRRORMODELREQUEST"]._serialized_start = 454
    _globals["_DELETEMIRRORMODELREQUEST"]._serialized_end = 568
    _globals["_DELETEMIRRORMODELRESPONSE"]._serialized_start = 570
    _globals["_DELETEMIRRORMODELRESPONSE"]._serialized_end = 672
    _globals["_MIRRORMODELSERVICE"]._serialized_start = 675
    _globals["_MIRRORMODELSERVICE"]._serialized_end = 1180
# @@protoc_insertion_point(module_scope)
