# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from omni_pro_grpc.v1.utilities import analytic_data_pb2 as v1_dot_utilities_dot_analytic__data__pb2


class AnalyticDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyticDataCreate = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.analytic_data.AnalyticDataService/AnalyticDataCreate",
            request_serializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataCreateRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataCreateResponse.FromString,
        )
        self.AnalyticDataRead = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.analytic_data.AnalyticDataService/AnalyticDataRead",
            request_serializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataReadRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataReadResponse.FromString,
        )
        self.AnalyticDataUpdate = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.analytic_data.AnalyticDataService/AnalyticDataUpdate",
            request_serializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataUpdateRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataUpdateResponse.FromString,
        )
        self.AnalyticDataDelete = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.analytic_data.AnalyticDataService/AnalyticDataDelete",
            request_serializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataDeleteRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataDeleteResponse.FromString,
        )


class AnalyticDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyticDataCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyticDataRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyticDataUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyticDataDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AnalyticDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AnalyticDataCreate": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyticDataCreate,
            request_deserializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataCreateRequest.FromString,
            response_serializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataCreateResponse.SerializeToString,
        ),
        "AnalyticDataRead": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyticDataRead,
            request_deserializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataReadRequest.FromString,
            response_serializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataReadResponse.SerializeToString,
        ),
        "AnalyticDataUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyticDataUpdate,
            request_deserializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataUpdateRequest.FromString,
            response_serializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataUpdateResponse.SerializeToString,
        ),
        "AnalyticDataDelete": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyticDataDelete,
            request_deserializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataDeleteRequest.FromString,
            response_serializer=v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataDeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pro.omni.oms.api.v1.utilities.analytic_data.AnalyticDataService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class AnalyticDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyticDataCreate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.analytic_data.AnalyticDataService/AnalyticDataCreate",
            v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataCreateRequest.SerializeToString,
            v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AnalyticDataRead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.analytic_data.AnalyticDataService/AnalyticDataRead",
            v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataReadRequest.SerializeToString,
            v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AnalyticDataUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.analytic_data.AnalyticDataService/AnalyticDataUpdate",
            v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataUpdateRequest.SerializeToString,
            v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AnalyticDataDelete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.analytic_data.AnalyticDataService/AnalyticDataDelete",
            v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataDeleteRequest.SerializeToString,
            v1_dot_utilities_dot_analytic__data__pb2.AnalyticDataDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
