# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from omni_pro_grpc.v1.utilities import cleaner_pb2 as v1_dot_utilities_dot_cleaner__pb2


class CleanerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CleanerCreate = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.cleaner.CleanerService/CleanerCreate",
            request_serializer=v1_dot_utilities_dot_cleaner__pb2.CleanerCreateRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_cleaner__pb2.CleanerCreateResponse.FromString,
        )
        self.CleanerRead = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.cleaner.CleanerService/CleanerRead",
            request_serializer=v1_dot_utilities_dot_cleaner__pb2.CleanerReadRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_cleaner__pb2.CleanerReadResponse.FromString,
        )
        self.CleanerUpdate = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.cleaner.CleanerService/CleanerUpdate",
            request_serializer=v1_dot_utilities_dot_cleaner__pb2.CleanerUpdateRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_cleaner__pb2.CleanerUpdateResponse.FromString,
        )
        self.CleanerDelete = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.cleaner.CleanerService/CleanerDelete",
            request_serializer=v1_dot_utilities_dot_cleaner__pb2.CleanerDeleteRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_cleaner__pb2.CleanerDeleteResponse.FromString,
        )


class CleanerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CleanerCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CleanerRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CleanerUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CleanerDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CleanerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CleanerCreate": grpc.unary_unary_rpc_method_handler(
            servicer.CleanerCreate,
            request_deserializer=v1_dot_utilities_dot_cleaner__pb2.CleanerCreateRequest.FromString,
            response_serializer=v1_dot_utilities_dot_cleaner__pb2.CleanerCreateResponse.SerializeToString,
        ),
        "CleanerRead": grpc.unary_unary_rpc_method_handler(
            servicer.CleanerRead,
            request_deserializer=v1_dot_utilities_dot_cleaner__pb2.CleanerReadRequest.FromString,
            response_serializer=v1_dot_utilities_dot_cleaner__pb2.CleanerReadResponse.SerializeToString,
        ),
        "CleanerUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.CleanerUpdate,
            request_deserializer=v1_dot_utilities_dot_cleaner__pb2.CleanerUpdateRequest.FromString,
            response_serializer=v1_dot_utilities_dot_cleaner__pb2.CleanerUpdateResponse.SerializeToString,
        ),
        "CleanerDelete": grpc.unary_unary_rpc_method_handler(
            servicer.CleanerDelete,
            request_deserializer=v1_dot_utilities_dot_cleaner__pb2.CleanerDeleteRequest.FromString,
            response_serializer=v1_dot_utilities_dot_cleaner__pb2.CleanerDeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pro.omni.oms.api.v1.utilities.cleaner.CleanerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class CleanerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CleanerCreate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.cleaner.CleanerService/CleanerCreate",
            v1_dot_utilities_dot_cleaner__pb2.CleanerCreateRequest.SerializeToString,
            v1_dot_utilities_dot_cleaner__pb2.CleanerCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CleanerRead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.cleaner.CleanerService/CleanerRead",
            v1_dot_utilities_dot_cleaner__pb2.CleanerReadRequest.SerializeToString,
            v1_dot_utilities_dot_cleaner__pb2.CleanerReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CleanerUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.cleaner.CleanerService/CleanerUpdate",
            v1_dot_utilities_dot_cleaner__pb2.CleanerUpdateRequest.SerializeToString,
            v1_dot_utilities_dot_cleaner__pb2.CleanerUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CleanerDelete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.cleaner.CleanerService/CleanerDelete",
            v1_dot_utilities_dot_cleaner__pb2.CleanerDeleteRequest.SerializeToString,
            v1_dot_utilities_dot_cleaner__pb2.CleanerDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
