# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from omni_pro_grpc.v1.utilities import dashboard_widget_pb2 as v1_dot_utilities_dot_dashboard__widget__pb2


class DashboardWidgetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DashboardWidgetCreate = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.dashboard_widget.DashboardWidgetService/DashboardWidgetCreate",
            request_serializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetCreateRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetCreateResponse.FromString,
        )
        self.DashboardWidgetRead = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.dashboard_widget.DashboardWidgetService/DashboardWidgetRead",
            request_serializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetReadRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetReadResponse.FromString,
        )
        self.DashboardWidgetUpdate = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.dashboard_widget.DashboardWidgetService/DashboardWidgetUpdate",
            request_serializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetUpdateRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetUpdateResponse.FromString,
        )
        self.DashboardWidgetDelete = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.dashboard_widget.DashboardWidgetService/DashboardWidgetDelete",
            request_serializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetDeleteRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetDeleteResponse.FromString,
        )


class DashboardWidgetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DashboardWidgetCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DashboardWidgetRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DashboardWidgetUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DashboardWidgetDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DashboardWidgetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "DashboardWidgetCreate": grpc.unary_unary_rpc_method_handler(
            servicer.DashboardWidgetCreate,
            request_deserializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetCreateRequest.FromString,
            response_serializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetCreateResponse.SerializeToString,
        ),
        "DashboardWidgetRead": grpc.unary_unary_rpc_method_handler(
            servicer.DashboardWidgetRead,
            request_deserializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetReadRequest.FromString,
            response_serializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetReadResponse.SerializeToString,
        ),
        "DashboardWidgetUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.DashboardWidgetUpdate,
            request_deserializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetUpdateRequest.FromString,
            response_serializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetUpdateResponse.SerializeToString,
        ),
        "DashboardWidgetDelete": grpc.unary_unary_rpc_method_handler(
            servicer.DashboardWidgetDelete,
            request_deserializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetDeleteRequest.FromString,
            response_serializer=v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetDeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pro.omni.oms.api.v1.utilities.dashboard_widget.DashboardWidgetService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class DashboardWidgetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DashboardWidgetCreate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.dashboard_widget.DashboardWidgetService/DashboardWidgetCreate",
            v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetCreateRequest.SerializeToString,
            v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DashboardWidgetRead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.dashboard_widget.DashboardWidgetService/DashboardWidgetRead",
            v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetReadRequest.SerializeToString,
            v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DashboardWidgetUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.dashboard_widget.DashboardWidgetService/DashboardWidgetUpdate",
            v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetUpdateRequest.SerializeToString,
            v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DashboardWidgetDelete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.dashboard_widget.DashboardWidgetService/DashboardWidgetDelete",
            v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetDeleteRequest.SerializeToString,
            v1_dot_utilities_dot_dashboard__widget__pb2.DashboardWidgetDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
