# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from omni_pro_grpc.v1.utilities import file_record_pb2 as v1_dot_utilities_dot_file__record__pb2


class FileRecordServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FileRecordAdd = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.file_record.FileRecordService/FileRecordAdd",
            request_serializer=v1_dot_utilities_dot_file__record__pb2.FileRecordAddRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_file__record__pb2.FileRecordAddResponse.FromString,
        )
        self.FileRecordRead = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.file_record.FileRecordService/FileRecordRead",
            request_serializer=v1_dot_utilities_dot_file__record__pb2.FileRecordReadRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_file__record__pb2.FileRecordReadResponse.FromString,
        )
        self.FileRecordUpdate = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.file_record.FileRecordService/FileRecordUpdate",
            request_serializer=v1_dot_utilities_dot_file__record__pb2.FileRecordUpdateRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_file__record__pb2.FileRecordUpdateResponse.FromString,
        )
        self.FileRecordDelete = channel.unary_unary(
            "/pro.omni.oms.api.v1.utilities.file_record.FileRecordService/FileRecordDelete",
            request_serializer=v1_dot_utilities_dot_file__record__pb2.FileRecordDeleteRequest.SerializeToString,
            response_deserializer=v1_dot_utilities_dot_file__record__pb2.FileRecordDeleteResponse.FromString,
        )


class FileRecordServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FileRecordAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FileRecordRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FileRecordUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FileRecordDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FileRecordServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "FileRecordAdd": grpc.unary_unary_rpc_method_handler(
            servicer.FileRecordAdd,
            request_deserializer=v1_dot_utilities_dot_file__record__pb2.FileRecordAddRequest.FromString,
            response_serializer=v1_dot_utilities_dot_file__record__pb2.FileRecordAddResponse.SerializeToString,
        ),
        "FileRecordRead": grpc.unary_unary_rpc_method_handler(
            servicer.FileRecordRead,
            request_deserializer=v1_dot_utilities_dot_file__record__pb2.FileRecordReadRequest.FromString,
            response_serializer=v1_dot_utilities_dot_file__record__pb2.FileRecordReadResponse.SerializeToString,
        ),
        "FileRecordUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.FileRecordUpdate,
            request_deserializer=v1_dot_utilities_dot_file__record__pb2.FileRecordUpdateRequest.FromString,
            response_serializer=v1_dot_utilities_dot_file__record__pb2.FileRecordUpdateResponse.SerializeToString,
        ),
        "FileRecordDelete": grpc.unary_unary_rpc_method_handler(
            servicer.FileRecordDelete,
            request_deserializer=v1_dot_utilities_dot_file__record__pb2.FileRecordDeleteRequest.FromString,
            response_serializer=v1_dot_utilities_dot_file__record__pb2.FileRecordDeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pro.omni.oms.api.v1.utilities.file_record.FileRecordService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class FileRecordService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FileRecordAdd(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.file_record.FileRecordService/FileRecordAdd",
            v1_dot_utilities_dot_file__record__pb2.FileRecordAddRequest.SerializeToString,
            v1_dot_utilities_dot_file__record__pb2.FileRecordAddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def FileRecordRead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.file_record.FileRecordService/FileRecordRead",
            v1_dot_utilities_dot_file__record__pb2.FileRecordReadRequest.SerializeToString,
            v1_dot_utilities_dot_file__record__pb2.FileRecordReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def FileRecordUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.file_record.FileRecordService/FileRecordUpdate",
            v1_dot_utilities_dot_file__record__pb2.FileRecordUpdateRequest.SerializeToString,
            v1_dot_utilities_dot_file__record__pb2.FileRecordUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def FileRecordDelete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pro.omni.oms.api.v1.utilities.file_record.FileRecordService/FileRecordDelete",
            v1_dot_utilities_dot_file__record__pb2.FileRecordDeleteRequest.SerializeToString,
            v1_dot_utilities_dot_file__record__pb2.FileRecordDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
